// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250411192223_general-migrations")]
    partial class generalmigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0c8e65b1-e7eb-4a9b-a958-5078f2810109",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "54ea22d5-ee3e-4ced-9a23-e93281293eef",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("api.Models.NewsSiteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSearchHttpGetBased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewSiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoliticalLeaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteUrlQueryString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Siteurl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NewsSite");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94f4bc7f-43c1-4c16-9d47-aaae4c5d09ff"),
                            IsSearchHttpGetBased = true,
                            NewSiteName = "LaNacion",
                            PoliticalLeaning = "Center-Right",
                            SiteUrlQueryString = "https://www.lanacion.com.ar/buscador/?query=",
                            Siteurl = "https://www.lanacion.com.ar"
                        },
                        new
                        {
                            Id = new Guid("cb51a47d-1b77-4440-a2c4-9f93f5275c06"),
                            IsSearchHttpGetBased = true,
                            NewSiteName = "TodoNoticias",
                            PoliticalLeaning = "Center-Right",
                            SiteUrlQueryString = "https://tn.com.ar/buscar/",
                            Siteurl = "https://tn.com.ar"
                        },
                        new
                        {
                            Id = new Guid("82ee607b-cee3-4b13-a23a-55b8411b6666"),
                            IsSearchHttpGetBased = true,
                            NewSiteName = "A24",
                            PoliticalLeaning = "Center",
                            SiteUrlQueryString = "https://www.a24.com/contenidos/resultado.html?search=",
                            Siteurl = "https://www.a24.com"
                        },
                        new
                        {
                            Id = new Guid("f4392654-788d-45fc-9057-2cce2930c2f6"),
                            IsSearchHttpGetBased = true,
                            NewSiteName = "Pagina12",
                            PoliticalLeaning = "Left",
                            SiteUrlQueryString = "https://www.pagina12.com.ar/buscar?q=",
                            Siteurl = "https://www.pagina12.com.ar"
                        },
                        new
                        {
                            Id = new Guid("82e2c7dd-2a02-48a9-b2b7-2843a97bd698"),
                            IsSearchHttpGetBased = true,
                            NewSiteName = "ElDestape",
                            PoliticalLeaning = "Left",
                            SiteUrlQueryString = "https://www.eldestapeweb.com/buscar/",
                            Siteurl = "https://www.eldestapeweb.com"
                        });
                });

            modelBuilder.Entity("api.NewsSiteSearchInfoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionClassName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsContainerClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsImageClassName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsSiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isMainSiteNews")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NewsSiteSearchInfo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13e4de78-0115-442f-b7c2-4eaeb3fe8949"),
                            DescriptionClassName = "queryly_item_description",
                            NewsContainerClassName = "queryly_item_row",
                            NewsSiteName = "LaNacion",
                            TitleClassName = "queryly_item_title",
                            isMainSiteNews = false
                        },
                        new
                        {
                            Id = new Guid("f5f023ef-d4c5-4f7d-bd49-e4bb918d3a77"),
                            DescriptionClassName = "card__subheadline",
                            NewsContainerClassName = "card__container",
                            NewsImageClassName = "image",
                            NewsSiteName = "TodoNoticias",
                            TitleClassName = "card__headline",
                            isMainSiteNews = false
                        },
                        new
                        {
                            Id = new Guid("007749e6-42ab-4a02-8947-d1544eb1700d"),
                            DescriptionClassName = "gs-bidi-start-align",
                            NewsContainerClassName = "gsc-webResult",
                            NewsImageClassName = "gs-image",
                            NewsSiteName = "A24",
                            TitleClassName = "gs-title",
                            isMainSiteNews = false
                        },
                        new
                        {
                            Id = new Guid("ed0bae73-9e76-4fb6-88c8-9dcec943b7f4"),
                            DescriptionClassName = "p12-separator--left--primary",
                            NewsContainerClassName = "article-item",
                            NewsImageClassName = "image",
                            NewsSiteName = "Pagina12",
                            TitleClassName = "title",
                            isMainSiteNews = false
                        },
                        new
                        {
                            Id = new Guid("647b6141-f11c-41fb-b0ec-3e207915db4c"),
                            NewsContainerClassName = "item-3",
                            NewsImageClassName = "lazyautosizes",
                            NewsSiteName = "ElDestape",
                            TitleClassName = "titulo",
                            isMainSiteNews = false
                        },
                        new
                        {
                            Id = new Guid("7980bb4c-3894-4d80-9994-773734af11db"),
                            DescriptionClassName = "subhead",
                            NewsContainerClassName = "grid-item",
                            NewsImageClassName = "image",
                            NewsSiteName = "LaNacion",
                            TitleClassName = "title",
                            isMainSiteNews = true
                        },
                        new
                        {
                            Id = new Guid("9fc0bf27-4606-43b0-882c-37394522eb93"),
                            DescriptionClassName = "card__subheadline",
                            NewsContainerClassName = "brick_one",
                            NewsImageClassName = "image",
                            NewsSiteName = "TodoNoticias",
                            TitleClassName = "card__headline",
                            isMainSiteNews = true
                        },
                        new
                        {
                            Id = new Guid("82ca2217-e582-4740-9129-94cb4ad5a3c1"),
                            DescriptionClassName = "ignore-parser",
                            NewsContainerClassName = "news-item",
                            NewsSiteName = "A24",
                            TitleClassName = "news-title",
                            isMainSiteNews = true
                        },
                        new
                        {
                            Id = new Guid("79e2a8d5-10c8-4d42-81be-650eeb4e7753"),
                            DescriptionClassName = "title-suffix",
                            NewsContainerClassName = "headline-card",
                            NewsImageClassName = "image",
                            NewsSiteName = "Pagina12",
                            TitleClassName = "title",
                            isMainSiteNews = true
                        },
                        new
                        {
                            Id = new Guid("b9124587-2def-4b02-b501-34cb4602a794"),
                            NewsContainerClassName = "item-6",
                            NewsImageClassName = "lazyautosizes",
                            NewsSiteName = "ElDestape",
                            TitleClassName = "titulo",
                            isMainSiteNews = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
